[package]
name = "gerenciador_biblioteca"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = "0.4.39"
ink = "4.0.0"
serde = "1.0.217"

[lib]
crate-type = ["cdylib", "rlib"]
